server:
  port: 8089

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${spring.application.name}/coordinator.db
  jooq:
    sql-dialect: SQLITE
  security:
    jwt:
      secret: "JwtSecretKey"
      expiration: 24 * 60 * 60 * 1000
  application:
    name: coordinator

sphynx:
  host: localhost
  socket:
    port: 1999
    maxWorkers: 50
    timeout: 5000
  allowedOrigin: http://localhost:8081
  


